'use strict';
const {clamp}=require('../core/prng');
const {applyStressEvent}=require('../state/stress');
const {remember}=require('../memory/memory');
const {maybeAcquireTrauma}=require('../state/trauma');
function peerTrustScore(npc,group){const peers=group.members.filter(n=>n.alive!==false&&n.npcId!==npc.npcId);if(!peers.length)return.5;return peers.reduce((sum,p)=>sum+(((p.relationships?.[npc.npcId]??0)+1)/2),0)/peers.length;}
function leadershipScore(npc,group){const t=npc.traits,s=npc.skills;const standing=npc.groupStanding??peerTrustScore(npc,group);return(t.leadership*.22+s.leadership*.18+t.discipline*.15+t.courage*.11+t.decisionConfidence*.09+t.loyalty*.07+standing*.18)*(1-(npc.stress||0)*.25);}
function selectLeader(group){const alive=group.members.filter(n=>n.alive!==false);if(!alive.length){group.leaderId=null;group.status='EMPTY';return null;}alive.sort((a,b)=>leadershipScore(b,group)-leadershipScore(a,group));const winner=alive[0];group.leaderId=winner.npcId;group.status='ACTIVE';for(const n of group.members)n.role=n.npcId===winner.npcId?'leader':'member';group.history.push({type:'leader_selected',npcId:winner.npcId,at:Date.now()});return winner;}
function onLeaderDeath(group,leaderId,{at=Date.now(),severity=1,stressEnabled=true}={}){group.status='LEADERLESS';group.leaderId=null;group.morale=clamp(group.morale-.32*severity);group.cohesion=clamp(group.cohesion-.28*severity);group.effects.leaderDeathShock=Math.max(group.effects.leaderDeathShock||0,.75*severity);group.successionAt=at+group.successionDelayMs;group.history.push({type:'leader_death',npcId:leaderId,at});for(const n of group.members.filter(n=>n.alive!==false)){if(n.npcId===leaderId){n.alive=false;continue;}const relation=n.relationships?.[leaderId]||0;if(stressEnabled)applyStressEvent(n,{type:'leader_death',intensity:.7+Math.max(0,relation)*.6,at});remember(n,{type:'leader_death',target:leaderId,importance:.95,at});if(stressEnabled&&(n.stress||0)>.72)maybeAcquireTrauma(n,{type:'leader_death',severity:Math.min(1,.65+Math.max(0,relation)*.35),source:leaderId,at,seed:`${group.groupId}:${at}`});}}
function processSuccession(group,{now=Date.now()}={}){if(group.status!=='LEADERLESS'||!group.successionAt||now<group.successionAt)return null;return selectLeader(group);}
function tickLeadership(group,dtSeconds){if((group.effects.leaderInjuryShock||0)>0)group.effects.leaderInjuryShock=clamp(group.effects.leaderInjuryShock-dtSeconds/600);if(group.effects.leaderDeathShock>0)group.effects.leaderDeathShock=clamp(group.effects.leaderDeathShock-dtSeconds/900);const leader=group.members.find(n=>n.npcId===group.leaderId&&n.alive!==false);if(leader){const calming=(leader.traits.composure*.015+leader.traits.leadership*.012)*dtSeconds;group.morale=clamp(group.morale+calming/60);group.cohesion=clamp(group.cohesion+calming/75);}}
function onLeaderInjured(group,leader,{severity=.5,at=Date.now(),stressEnabled=true}={}){if(!leader||leader.npcId!==group.leaderId||leader.alive===false)return;const shock=clamp(.08+.22*severity);group.morale=clamp(group.morale-shock);group.cohesion=clamp(group.cohesion-shock*.6);group.effects.leaderInjuryShock=Math.max(group.effects.leaderInjuryShock||0,.45*severity);group.history.push({type:'leader_injured',npcId:leader.npcId,severity,at});for(const n of group.members.filter(n=>n.alive!==false&&n.npcId!==leader.npcId)){if(stressEnabled)applyStressEvent(n,{type:'wound',intensity:.5+severity*.5,at});remember(n,{type:'leader_injured',target:leader.npcId,importance:.7+severity*.2,at});}}
module.exports={leadershipScore,peerTrustScore,selectLeader,onLeaderDeath,onLeaderInjured,processSuccession,tickLeadership};
