# SmartNPC :: lib.ps1
# Shared helpers for INSTALL / REPAIR / UNINSTALL / STATUS.
# Dot-sourced; defines functions only.

<#
    Reads a property that may not exist.  Under Set-StrictMode, touching a
    missing property throws, and both the install manifest and the telemetry
    snapshot are files written by an older version whose shape we cannot assume.
#>
function Get-Prop {
    param($Object, [string]$Name, $Default = $null)
    if ($null -eq $Object) { return $Default }
    try {
        $p = $Object.PSObject.Properties[$Name]
        if ($null -eq $p -or $null -eq $p.Value) { return $Default }
        return $p.Value
    } catch { return $Default }
}

function Find-ScumServer {
    param([string]$Hint = '', [string]$SelfDir = '')

    $candidates = @()
    if ($Hint) { $candidates += $Hint }
    # When a script runs from <server>\SmartNPC, the server is its parent.
    if ($SelfDir) { $candidates += (Split-Path -Parent $SelfDir) }
    $candidates += @(
        'F:\SteamLibrary\steamapps\common\SCUM Server',
        'E:\SteamLibrary\steamapps\common\SCUM Server',
        'D:\SteamLibrary\steamapps\common\SCUM Server',
        'C:\SteamLibrary\steamapps\common\SCUM Server',
        'C:\Program Files (x86)\Steam\steamapps\common\SCUM Server',
        'C:\Program Files\Steam\steamapps\common\SCUM Server'
    )
    foreach ($d in (Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)) {
        $candidates += (Join-Path $d.Root 'SteamLibrary\steamapps\common\SCUM Server')
        $candidates += (Join-Path $d.Root 'SCUM Server')
    }
    foreach ($c in ($candidates | Select-Object -Unique)) {
        if (-not $c) { continue }
        try {
            if (Test-Path -LiteralPath (Join-Path $c 'SCUM\Binaries\Win64\SCUMServer.exe') -PathType Leaf) {
                return (Resolve-Path -LiteralPath $c).Path
            }
        } catch {}
    }
    return $null
}

<#
    UE4SS has shipped two layouts:
      2.x :  <Win64>\UE4SS.dll        mods in <Win64>\Mods         list <Win64>\Mods\mods.txt
      3.x :  <Win64>\ue4ss\UE4SS.dll  mods in <Win64>\ue4ss\Mods   list <Win64>\ue4ss\Mods\mods.txt

    Guessing wrong means the loader is written somewhere UE4SS never reads, and
    the mod silently never starts.  So: return every plausible mods root, most
    likely first, and let the caller install into all of them.  A loader stub in
    an unused folder is inert.
#>
function Get-UE4SSLayout {
    param([Parameter(Mandatory = $true)][string]$Win64)

    $roots = @()

    $modern = Join-Path $Win64 'ue4ss'
    $modernMods = Join-Path $modern 'Mods'
    $legacyMods = Join-Path $Win64 'Mods'

    $modernDll = (Test-Path -LiteralPath (Join-Path $modern 'UE4SS.dll') -PathType Leaf)
    $legacyDll = (Test-Path -LiteralPath (Join-Path $Win64 'UE4SS.dll') -PathType Leaf)

    # An existing Mods folder is the strongest signal: that is where the
    # installed UE4SS actually keeps things.
    if (Test-Path -LiteralPath $modernMods -PathType Container) { $roots += $modernMods }
    if (Test-Path -LiteralPath $legacyMods -PathType Container) { $roots += $legacyMods }

    if ($roots.Count -eq 0) {
        if ($modernDll) { $roots += $modernMods }
        elseif ($legacyDll) { $roots += $legacyMods }
        else { $roots += $legacyMods }
    }

    [pscustomobject]@{
        Win64     = $Win64
        ModsRoots = @($roots | Select-Object -Unique)
        Dll       = $(if ($legacyDll) { Join-Path $Win64 'UE4SS.dll' }
                      elseif ($modernDll) { Join-Path $modern 'UE4SS.dll' }
                      else { $null })
        HasUE4SS  = ($legacyDll -or $modernDll)
    }
}

# UE4SS writes its log next to the DLL in 2.x and inside ue4ss\ in 3.x.
function Get-UE4SSLogPath {
    param([Parameter(Mandatory = $true)][string]$Win64)
    foreach ($p in @(
        (Join-Path $Win64 'UE4SS.log'),
        (Join-Path $Win64 'ue4ss\UE4SS.log'),
        (Join-Path $Win64 'ue4ss\UE4SS-log.txt'),
        (Join-Path $Win64 'UE4SS-log.txt')
    )) {
        if (Test-Path -LiteralPath $p -PathType Leaf) { return $p }
    }
    return $null
}

function Write-LoaderStub {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [Parameter(Mandatory = $true)][string]$ModHome
    )
    $stub = Join-Path $ModsRoot 'SmartNPC'
    New-Item -ItemType Directory -Path (Join-Path $stub 'Scripts') -Force | Out-Null

    $lua = @"
-- SmartNPC loader stub.
-- Generated by the SmartNPC installer - do not edit.
-- All SmartNPC code, data, config, state and logs live in the folder below.
SMARTNPC_ROOT = [[$ModHome]]
local ok, err = pcall(dofile, SMARTNPC_ROOT .. "\\lua\\boot.lua")
if not ok then
    print("[SmartNPC] boot failed: " .. tostring(err) .. "\n")
end
"@
    $enc = New-Object Text.UTF8Encoding($false)
    [IO.File]::WriteAllText((Join-Path $stub 'Scripts\main.lua'), $lua, $enc)
    return $stub
}

<#
    mods.txt is the documented way to enable a mod and it carries the load
    order.  enabled.txt is only a fallback: on some builds its presence makes
    UE4SS ignore mods.txt entirely, so it is written only when the mods.txt
    entry could not be verified, and removed again once mods.txt works.
#>
function Set-EnabledTxt {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [Parameter(Mandatory = $true)][bool]$Wanted
    )
    $path = Join-Path $ModsRoot 'SmartNPC\enabled.txt'
    if ($Wanted) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            [IO.File]::WriteAllText($path, '', (New-Object Text.UTF8Encoding($false)))
        }
    } elseif (Test-Path -LiteralPath $path -PathType Leaf) {
        Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
    }
}

function Set-ModsTxtEntry {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [switch]$Remove
    )
    $path = Join-Path $ModsRoot 'mods.txt'
    $existed = Test-Path -LiteralPath $path -PathType Leaf
    $lines = @()
    if ($existed) {
        $lines = @(Get-Content -LiteralPath $path -Encoding UTF8 -ErrorAction SilentlyContinue)
    }
    $lines = @($lines | Where-Object { $_ -notmatch '^\s*SmartNPC\s*:' })
    if (-not $Remove) { $lines += 'SmartNPC : 1' }

    if ($Remove -and -not $existed) { return [pscustomobject]@{ Path = $path; Existed = $false; Ok = $true } }

    New-Item -ItemType Directory -Path $ModsRoot -Force | Out-Null
    [IO.File]::WriteAllLines($path, [string[]]$lines, (New-Object Text.UTF8Encoding($false)))

    # Read back: a silently failed write here is the difference between a mod
    # that runs and a mod that never starts.
    $ok = $true
    if (-not $Remove) {
        $ok = [bool](Get-Content -LiteralPath $path -Encoding UTF8 -ErrorAction SilentlyContinue |
                     Where-Object { $_ -match '^\s*SmartNPC\s*:\s*1\s*$' })
    }
    [pscustomobject]@{ Path = $path; Existed = $existed; Ok = $ok }
}

function Test-SmartNPCLoader {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [Parameter(Mandatory = $true)][string]$ModHome
    )
    $stub = Join-Path $ModsRoot 'SmartNPC\Scripts\main.lua'
    $stubOk = Test-Path -LiteralPath $stub -PathType Leaf
    $pointsHere = $false
    if ($stubOk) {
        $txt = Get-Content -LiteralPath $stub -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
        $pointsHere = $txt -and $txt.Contains($ModHome)
    }
    $modsTxt = Join-Path $ModsRoot 'mods.txt'
    $listed = $false
    if (Test-Path -LiteralPath $modsTxt -PathType Leaf) {
        $listed = [bool](Get-Content -LiteralPath $modsTxt -Encoding UTF8 -ErrorAction SilentlyContinue |
                         Where-Object { $_ -match '^\s*SmartNPC\s*:\s*1\s*$' })
    }
    [pscustomobject]@{
        ModsRoot   = $ModsRoot
        Stub       = $stub
        StubOk     = $stubOk
        PointsHere = $pointsHere
        Enabled    = (Test-Path -LiteralPath (Join-Path $ModsRoot 'SmartNPC\enabled.txt') -PathType Leaf)
        Listed     = $listed
        ModsTxt    = $modsTxt
    }
}

<#
    A running SmartNPC map server keeps a PowerShell process alive whose working
    directory is the mod folder, which locks the folder against deletion.  Find
    those processes by command line so the installer can close them instead of
    failing with "used by another process".
#>
function Get-MapServerProcess {
    param([string]$ModHome = '')
    $out = @()
    try {
        $procs = Get-CimInstance Win32_Process -ErrorAction Stop |
                 Where-Object { $_.Name -in @('powershell.exe','pwsh.exe') -and $_.CommandLine }
        foreach ($p in $procs) {
            if ($p.CommandLine -match 'START_MAP\.ps1') {
                if (-not $ModHome -or $p.CommandLine -like ("*" + $ModHome + "*")) { $out += $p }
            }
        }
    } catch {}
    return $out
}

function Stop-MapServer {
    param([string]$ModHome = '')
    $procs = @(Get-MapServerProcess -ModHome $ModHome)
    $stopped = 0
    foreach ($p in $procs) {
        try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop; $stopped++ } catch {}
    }
    if ($stopped -gt 0) { Start-Sleep -Milliseconds 700 }
    return $stopped
}

<#
    Update the mod in place instead of deleting and re-creating the folder.

    Deleting the folder fails whenever anything holds a handle on it - an open
    Explorer window, a map server, a text editor - and the old installer then
    aborted having already made a backup.  Copying file by file only needs the
    individual files to be writable, and never touches state, output, logs or
    tools.
#>
function Sync-ModFiles {
    param(
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string]$Dest,
        [string[]]$CodeDirs = @('lua','data','web'),
        # The user's folders. Nothing in them is ever read from the package or
        # written over, even if a package accidentally ships something there.
        [string[]]$UserDirs = @('state','output','logs','tools')
    )
    $failed = @()
    $copied = 0

    New-Item -ItemType Directory -Path $Dest -Force | Out-Null
    foreach ($d in $UserDirs) {
        New-Item -ItemType Directory -Path (Join-Path $Dest $d) -Force | Out-Null
    }

    $srcRoot = (Resolve-Path -LiteralPath $Source).Path.TrimEnd('\','/')
    $files = Get-ChildItem -LiteralPath $Source -Recurse -File -Force
    $wanted = New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)

    foreach ($f in $files) {
        $rel = $f.FullName.Substring($srcRoot.Length).TrimStart('\','/')
        $top = ($rel -split '[\\/]')[0]
        if ($UserDirs -contains $top) { continue }
        [void]$wanted.Add($rel)
        $target = Join-Path $Dest $rel
        $targetDir = Split-Path -Parent $target
        if (-not (Test-Path -LiteralPath $targetDir)) {
            New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
        }
        try {
            # A stale directory sitting where a file belongs would silently turn
            # into a copy *inside* it, leaving a broken install that reports
            # success. Clear it first.
            if (Test-Path -LiteralPath $target -PathType Container) {
                Remove-Item -LiteralPath $target -Recurse -Force -ErrorAction Stop
            }
            Copy-Item -LiteralPath $f.FullName -Destination $target -Force -ErrorAction Stop
            if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { throw 'file not present after copy' }
            $copied++
        } catch {
            $failed += $rel
        }
    }

    # Remove code files this version no longer ships, so an upgrade cannot leave
    # a stale module behind.  Only inside the code folders: state, output, logs
    # and tools are the user's and are never enumerated here.
    foreach ($dir in $CodeDirs) {
        $d = Join-Path $Dest $dir
        if (-not (Test-Path -LiteralPath $d -PathType Container)) { continue }
        $dRootLen = ((Resolve-Path -LiteralPath $Dest).Path.TrimEnd('\','/')).Length
        foreach ($existing in (Get-ChildItem -LiteralPath $d -Recurse -File -Force)) {
            $rel = $existing.FullName.Substring($dRootLen).TrimStart('\','/')
            if (-not $wanted.Contains($rel)) {
                Remove-Item -LiteralPath $existing.FullName -Force -ErrorAction SilentlyContinue
            }
        }
    }

    [pscustomobject]@{ Copied = $copied; Failed = @($failed) }
}

<#
    SmartNPC 1.0.0 and 1.0.1 could download UE4SS when they did not find
    Win64\UE4SS.dll.  On a SCUM server whose UE4SS lives in Win64\ue4ss\ that
    check was wrong: the download landed a second, generic UE4SS (including its
    dwmapi.dll proxy) at Win64 root, where it takes over loading and then dies
    on SCUM's build - after which no Lua mod loads at all.

    This undoes exactly that, and only that: a file is removed only when it is
    byte-for-byte the copy SmartNPC extracted, so anything the user has since
    replaced or edited is left alone.
#>
function Get-DownloadedUE4SSFiles {
    param(
        [Parameter(Mandatory = $true)][string]$ModHome,
        [Parameter(Mandatory = $true)][string]$Win64
    )
    $extracted = Join-Path $ModHome 'tools\ue4ss\extracted'
    if (-not (Test-Path -LiteralPath $extracted -PathType Container)) { return @() }

    $root = (Resolve-Path -LiteralPath $extracted).Path.TrimEnd('\','/')
    $out = @()
    foreach ($f in (Get-ChildItem -LiteralPath $extracted -Recurse -File -Force)) {
        $rel = $f.FullName.Substring($root.Length).TrimStart('\','/')
        $target = Join-Path $Win64 $rel
        if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { continue }
        $same = $false
        try {
            $a = Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256
            $b = Get-FileHash -LiteralPath $target -Algorithm SHA256
            $same = ($a.Hash -eq $b.Hash)
        } catch {}
        $out += [pscustomobject]@{ Relative = $rel; Path = $target; Unchanged = $same }
    }
    return $out
}

function Remove-DownloadedUE4SS {
    param(
        [Parameter(Mandatory = $true)][string]$ModHome,
        [Parameter(Mandatory = $true)][string]$Win64
    )
    $files = @(Get-DownloadedUE4SSFiles -ModHome $ModHome -Win64 $Win64)
    $removed = 0; $kept = @()
    foreach ($f in $files) {
        if ($f.Unchanged) {
            try { Remove-Item -LiteralPath $f.Path -Force -ErrorAction Stop; $removed++ } catch { $kept += $f.Relative }
        } else {
            $kept += $f.Relative
        }
    }
    # prune directories the download created and that are now empty
    for ($pass = 0; $pass -lt 4; $pass++) {
        foreach ($d in (Get-ChildItem -LiteralPath $Win64 -Recurse -Directory -Force -ErrorAction SilentlyContinue |
                        Sort-Object { $_.FullName.Length } -Descending)) {
            if (-not (Get-ChildItem -LiteralPath $d.FullName -Force -ErrorAction SilentlyContinue)) {
                Remove-Item -LiteralPath $d.FullName -Force -ErrorAction SilentlyContinue
            }
        }
    }
    [pscustomobject]@{ Removed = $removed; Kept = @($kept); Total = $files.Count }
}

# Read UE4SS's own log and decide whether UE4SS itself is healthy.  When its
# pattern scan fails, no Lua mod loads and nothing about SmartNPC matters.
function Test-UE4SSHealth {
    param([Parameter(Mandatory = $true)][string]$Win64)
    $log = Get-UE4SSLogPath -Win64 $Win64
    if (-not $log) { return [pscustomobject]@{ Log = $null; Fatal = $false; Reason = 'no UE4SS log yet'; Version = $null } }
    $text = ''
    try { $text = Get-Content -LiteralPath $log -Raw -Encoding UTF8 -ErrorAction Stop } catch {}
    $version = $null
    if ($text -match 'UE4SS\s*-\s*(v[\d\.]+[^\r\n#]*)') { $version = $Matches[1].Trim() }
    $fatal = $false; $reason = 'looks healthy'
    if ($text -match 'PS scan timed out') { $fatal = $true; $reason = 'UE4SS pattern scan timed out - UE4SS never started, so no mod loaded' }
    elseif ($text -match 'Scan failed') { $fatal = $true; $reason = 'UE4SS pattern scan failed - UE4SS cannot attach to this game build' }
    elseif ($text -match 'Fatal Error') { $fatal = $true; $reason = 'UE4SS reported a fatal error' }
    [pscustomobject]@{ Log = $log; Fatal = $fatal; Reason = $reason; Version = $version }
}
