# SmartNPC :: lib.ps1
# Shared helpers for INSTALL / REPAIR / UNINSTALL / STATUS.
# Dot-sourced; defines functions only.

function Find-ScumServer {
    param([string]$Hint = '', [string]$SelfDir = '')

    $candidates = @()
    if ($Hint) { $candidates += $Hint }
    # When a script runs from <server>\SmartNPC, the server is its parent.
    if ($SelfDir) { $candidates += (Split-Path -Parent $SelfDir) }
    $candidates += @(
        'F:\SteamLibrary\steamapps\common\SCUM Server',
        'E:\SteamLibrary\steamapps\common\SCUM Server',
        'D:\SteamLibrary\steamapps\common\SCUM Server',
        'C:\SteamLibrary\steamapps\common\SCUM Server',
        'C:\Program Files (x86)\Steam\steamapps\common\SCUM Server',
        'C:\Program Files\Steam\steamapps\common\SCUM Server'
    )
    foreach ($d in (Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)) {
        $candidates += (Join-Path $d.Root 'SteamLibrary\steamapps\common\SCUM Server')
        $candidates += (Join-Path $d.Root 'SCUM Server')
    }
    foreach ($c in ($candidates | Select-Object -Unique)) {
        if (-not $c) { continue }
        try {
            if (Test-Path -LiteralPath (Join-Path $c 'SCUM\Binaries\Win64\SCUMServer.exe') -PathType Leaf) {
                return (Resolve-Path -LiteralPath $c).Path
            }
        } catch {}
    }
    return $null
}

<#
    UE4SS has shipped two layouts:
      2.x :  <Win64>\UE4SS.dll        mods in <Win64>\Mods         list <Win64>\Mods\mods.txt
      3.x :  <Win64>\ue4ss\UE4SS.dll  mods in <Win64>\ue4ss\Mods   list <Win64>\ue4ss\Mods\mods.txt

    Guessing wrong means the loader is written somewhere UE4SS never reads, and
    the mod silently never starts.  So: return every plausible mods root, most
    likely first, and let the caller install into all of them.  A loader stub in
    an unused folder is inert.
#>
function Get-UE4SSLayout {
    param([Parameter(Mandatory = $true)][string]$Win64)

    $roots = @()

    $modern = Join-Path $Win64 'ue4ss'
    $modernMods = Join-Path $modern 'Mods'
    $legacyMods = Join-Path $Win64 'Mods'

    $modernDll = (Test-Path -LiteralPath (Join-Path $modern 'UE4SS.dll') -PathType Leaf)
    $legacyDll = (Test-Path -LiteralPath (Join-Path $Win64 'UE4SS.dll') -PathType Leaf)

    # An existing Mods folder is the strongest signal: that is where the
    # installed UE4SS actually keeps things.
    if (Test-Path -LiteralPath $modernMods -PathType Container) { $roots += $modernMods }
    if (Test-Path -LiteralPath $legacyMods -PathType Container) { $roots += $legacyMods }

    if ($roots.Count -eq 0) {
        if ($modernDll) { $roots += $modernMods }
        elseif ($legacyDll) { $roots += $legacyMods }
        else { $roots += $legacyMods }
    }

    [pscustomobject]@{
        Win64     = $Win64
        ModsRoots = @($roots | Select-Object -Unique)
        Dll       = $(if ($legacyDll) { Join-Path $Win64 'UE4SS.dll' }
                      elseif ($modernDll) { Join-Path $modern 'UE4SS.dll' }
                      else { $null })
        HasUE4SS  = ($legacyDll -or $modernDll)
    }
}

# UE4SS writes its log next to the DLL in 2.x and inside ue4ss\ in 3.x.
function Get-UE4SSLogPath {
    param([Parameter(Mandatory = $true)][string]$Win64)
    foreach ($p in @(
        (Join-Path $Win64 'UE4SS.log'),
        (Join-Path $Win64 'ue4ss\UE4SS.log'),
        (Join-Path $Win64 'ue4ss\UE4SS-log.txt'),
        (Join-Path $Win64 'UE4SS-log.txt')
    )) {
        if (Test-Path -LiteralPath $p -PathType Leaf) { return $p }
    }
    return $null
}

function Write-LoaderStub {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [Parameter(Mandatory = $true)][string]$ModHome
    )
    $stub = Join-Path $ModsRoot 'SmartNPC'
    New-Item -ItemType Directory -Path (Join-Path $stub 'Scripts') -Force | Out-Null

    $lua = @"
-- SmartNPC loader stub.
-- Generated by the SmartNPC installer - do not edit.
-- All SmartNPC code, data, config, state and logs live in the folder below.
SMARTNPC_ROOT = [[$ModHome]]
local ok, err = pcall(dofile, SMARTNPC_ROOT .. "\\lua\\boot.lua")
if not ok then
    print("[SmartNPC] boot failed: " .. tostring(err) .. "\n")
end
"@
    $enc = New-Object Text.UTF8Encoding($false)
    [IO.File]::WriteAllText((Join-Path $stub 'Scripts\main.lua'), $lua, $enc)
    # UE4SS 3.x enables a mod by the presence of this file; 2.x uses mods.txt.
    # Writing both makes the mod load whichever version is installed.
    [IO.File]::WriteAllText((Join-Path $stub 'enabled.txt'), '', $enc)
    return $stub
}

function Set-ModsTxtEntry {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [switch]$Remove
    )
    $path = Join-Path $ModsRoot 'mods.txt'
    $existed = Test-Path -LiteralPath $path -PathType Leaf
    $lines = @()
    if ($existed) {
        $lines = @(Get-Content -LiteralPath $path -Encoding UTF8 -ErrorAction SilentlyContinue)
    }
    $lines = @($lines | Where-Object { $_ -notmatch '^\s*SmartNPC\s*:' })
    if (-not $Remove) { $lines += 'SmartNPC : 1' }

    if ($Remove -and -not $existed) { return [pscustomobject]@{ Path = $path; Existed = $false; Ok = $true } }

    New-Item -ItemType Directory -Path $ModsRoot -Force | Out-Null
    [IO.File]::WriteAllLines($path, [string[]]$lines, (New-Object Text.UTF8Encoding($false)))

    # Read back: a silently failed write here is the difference between a mod
    # that runs and a mod that never starts.
    $ok = $true
    if (-not $Remove) {
        $ok = [bool](Get-Content -LiteralPath $path -Encoding UTF8 -ErrorAction SilentlyContinue |
                     Where-Object { $_ -match '^\s*SmartNPC\s*:\s*1\s*$' })
    }
    [pscustomobject]@{ Path = $path; Existed = $existed; Ok = $ok }
}

function Test-SmartNPCLoader {
    param(
        [Parameter(Mandatory = $true)][string]$ModsRoot,
        [Parameter(Mandatory = $true)][string]$ModHome
    )
    $stub = Join-Path $ModsRoot 'SmartNPC\Scripts\main.lua'
    $stubOk = Test-Path -LiteralPath $stub -PathType Leaf
    $pointsHere = $false
    if ($stubOk) {
        $txt = Get-Content -LiteralPath $stub -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
        $pointsHere = $txt -and $txt.Contains($ModHome)
    }
    $modsTxt = Join-Path $ModsRoot 'mods.txt'
    $listed = $false
    if (Test-Path -LiteralPath $modsTxt -PathType Leaf) {
        $listed = [bool](Get-Content -LiteralPath $modsTxt -Encoding UTF8 -ErrorAction SilentlyContinue |
                         Where-Object { $_ -match '^\s*SmartNPC\s*:\s*1\s*$' })
    }
    [pscustomobject]@{
        ModsRoot   = $ModsRoot
        Stub       = $stub
        StubOk     = $stubOk
        PointsHere = $pointsHere
        Enabled    = (Test-Path -LiteralPath (Join-Path $ModsRoot 'SmartNPC\enabled.txt') -PathType Leaf)
        Listed     = $listed
        ModsTxt    = $modsTxt
    }
}
