'use strict';
const {createRng,clamp}=require('../core/prng');
const {recomputeGroupStats}=require('../groups/cohesion');
const {onLeaderDeath}=require('../groups/leadership');
const {remember}=require('../memory/memory');
const {applyStressEvent}=require('../state/stress');
const {maybeAcquireTrauma}=require('../state/trauma');
const {adjustGroupRelation}=require('../groups/diplomacy');
function casualtyChance(powerOwn,powerEnemy,duration){return clamp((powerEnemy/(powerOwn+powerEnemy+.01))*(duration/180)*.7,0,.85);}
function killNpc(group,npc,enemyId,at,{stressEnabled=true}={}){npc.alive=false;npc.health=0;group.history.push({type:'casualty',npcId:npc.npcId,enemyGroupId:enemyId,at});for(const s of group.members.filter(x=>x.alive!==false)){if(stressEnabled)applyStressEvent(s,{type:'friend_death',intensity:1,at});remember(s,{type:'friend_death',target:npc.npcId,enemyGroupId:enemyId,importance:.85,at});if(stressEnabled&&s.stress>.78)maybeAcquireTrauma(s,{type:'witness_death',severity:.8,source:npc.npcId,at,seed:`${group.groupId}-${npc.npcId}`});}if(group.leaderId===npc.npcId)onLeaderDeath(group,npc.npcId,{at,severity:1,stressEnabled});}
function resolveVirtualGroupCombat(a,b,{seed='combat',durationSeconds=60,at=Date.now(),stressEnabled=true}={}){recomputeGroupStats(a);recomputeGroupStats(b);const rng=createRng(seed);const casualties={a:[],b:[]};const events=[];const pa=Math.max(.1,a.combatPower),pb=Math.max(.1,b.combatPower);for(const [group,enemy,pOwn,pEnemy,key] of [[a,b,pa,pb,'a'],[b,a,pb,pa,'b']]){for(const n of group.members.filter(n=>n.alive!==false)){const skill=(n.skills.tacticalMovement+n.skills.coverUsage+n.skills.rifle)/3;const chance=casualtyChance(pOwn,pEnemy,durationSeconds)*(1-skill*.45)*(1+(n.stress||0)*.25);if(rng()<chance){killNpc(group,n,enemy.groupId,at,{stressEnabled});casualties[key].push(n.npcId);events.push({type:'npc_killed',npcId:n.npcId,groupId:group.groupId,enemyGroupId:enemy.groupId,at});}}}recomputeGroupStats(a);recomputeGroupStats(b);let winner='draw';if(a.combatPower>b.combatPower*1.15)winner='a';else if(b.combatPower>a.combatPower*1.15)winner='b';if(winner==='a'){b.morale=clamp(b.morale-.22);events.push({type:'group_retreat',groupId:b.groupId});}else if(winner==='b'){a.morale=clamp(a.morale-.22);events.push({type:'group_retreat',groupId:a.groupId});}adjustGroupRelation(a,b.groupId,-.08-.10*casualties.a.length);adjustGroupRelation(b,a.groupId,-.08-.10*casualties.b.length);a.history.push({type:'combat',enemyGroupId:b.groupId,winner:winner==='a',at});b.history.push({type:'combat',enemyGroupId:a.groupId,winner:winner==='b',at});return{winner,casualties,events};}
module.exports={resolveVirtualGroupCombat};
