'use strict';
const http=require('http'); const fs=require('fs'); const path=require('path');
const {WorldDirector}=require('./director/worldDirector'); const {loadWorld,saveWorld}=require('./persistence/worldStore'); const {parseEventLine,formatCommand}=require('./bridge/protocol');
function finiteNumber(v,name){const n=Number(v);if(!Number.isFinite(n))throw new TypeError(`${name} must be a finite number`);return n;}
function buildTeleportCommand(pos,player=''){const x=finiteNumber(pos.x,'x'),y=finiteNumber(pos.y,'y'),z=finiteNumber(pos.z,'z');return `#Teleport ${x} ${y} ${z}${player?` ${String(player).trim()}`:''}`;}
function sendJson(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(body);}
function staticType(file){const e=path.extname(file).toLowerCase();return e==='.html'?'text/html; charset=utf-8':e==='.js'?'application/javascript; charset=utf-8':e==='.css'?'text/css; charset=utf-8':e==='.png'?'image/png':'application/octet-stream';}
function safeStaticFile(publicDir,urlPath){const root=path.resolve(publicDir);const rel=path.normalize(urlPath==='/'?'index.html':urlPath.replace(/^[/\\]+/,''));const file=path.resolve(root,rel);const relative=path.relative(root,file);if(relative.startsWith('..')||path.isAbsolute(relative))return null;return file;}
function createHttpServer({director,publicDir,mapConfig={}}){return http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/snapshot')return sendJson(res,200,director.snapshot());if(u.pathname==='/api/map-snapshot')return sendJson(res,200,director.compactSnapshot());if(u.pathname.startsWith('/api/npc/')){const id=decodeURIComponent(u.pathname.slice('/api/npc/'.length));const d=director.npcDetails(id);return d?sendJson(res,200,d):sendJson(res,404,{error:'npc not found'});}if(u.pathname==='/api/health')return sendJson(res,200,director.healthSnapshot());if(u.pathname==='/api/map-config')return sendJson(res,200,mapConfig);if(u.pathname==='/api/teleport'){try{const x=finiteNumber(u.searchParams.get('x'),'x'),y=finiteNumber(u.searchParams.get('y'),'y');const rawZ=u.searchParams.get('z');if(rawZ==null||rawZ==='')throw new TypeError('z is required because SCUM #Teleport requires X Y Z');const z=finiteNumber(rawZ,'z');const player=u.searchParams.get('player')||'';return sendJson(res,200,{command:buildTeleportCommand({x,y,z},player)});}catch(err){return sendJson(res,400,{error:err.message});}}if(!publicDir)return sendJson(res,404,{error:'not found'});const file=safeStaticFile(publicDir,u.pathname);if(!file||!fs.existsSync(file)||fs.statSync(file).isDirectory())return sendJson(res,404,{error:'not found'});res.writeHead(200,{'content-type':staticType(file)});fs.createReadStream(file).pipe(res);}catch(err){sendJson(res,500,{error:err.message});}});}
class FileIpcReader{
 constructor(file,offsetFile=null){this.file=file;this.offsetFile=offsetFile;this.offset=0;this.fileId=null;this._loadOffset();if(!this.fileId&&fs.existsSync(this.file)){try{this.fileId=this._fileId(fs.statSync(this.file));}catch{}}}
 _fileId(st){if(!st)return null;return `${st.dev??''}:${st.ino??''}:${st.birthtimeMs??''}`;}
 _loadOffset(){if(!this.offsetFile||!fs.existsSync(this.offsetFile))return;try{const d=JSON.parse(fs.readFileSync(this.offsetFile,'utf8'));if(d.file===path.resolve(this.file)&&Number.isSafeInteger(d.offset)&&d.offset>=0){this.offset=d.offset;this.fileId=typeof d.fileId==='string'&&d.fileId?d.fileId:null;}}catch{} }
 _saveOffset(){if(!this.offsetFile)return;fs.mkdirSync(path.dirname(this.offsetFile),{recursive:true});const tmp=this.offsetFile+'.tmp';fs.writeFileSync(tmp,JSON.stringify({version:2,file:path.resolve(this.file),fileId:this.fileId,offset:this.offset,updatedAt:Date.now()}));fs.renameSync(tmp,this.offsetFile);}
 _readComplete(file,start,onEvent){if(!fs.existsSync(file))return start;const st=fs.statSync(file);if(st.size<=start)return start;const fd=fs.openSync(file,'r');try{const len=st.size-start;const buf=Buffer.alloc(len);fs.readSync(fd,buf,0,len,start);let lastNl=-1;for(let i=buf.length-1;i>=0;i--){if(buf[i]===10){lastNl=i;break;}}if(lastNl<0)return start;const complete=buf.subarray(0,lastNl+1).toString('utf8');for(const line of complete.split(/\r?\n/)){if(!line.trim())continue;const e=parseEventLine(line);if(e)onEvent(e);}return start+lastNl+1;}finally{fs.closeSync(fd);}}
 poll(onEvent){if(!fs.existsSync(this.file))return;let st=fs.statSync(this.file);const currentId=this._fileId(st);const replaced=Boolean(this.fileId&&currentId&&this.fileId!==currentId);if(replaced||st.size<this.offset){const rotated=this.file+'.1';if(fs.existsSync(rotated))this._readComplete(rotated,this.offset,onEvent);this.offset=0;this.fileId=currentId;this._saveOffset();st=fs.statSync(this.file);}else if(!this.fileId){this.fileId=currentId;this._saveOffset();}if(st.size===this.offset)return;this.offset=this._readComplete(this.file,this.offset,onEvent);this.fileId=currentId;this._saveOffset();}
}
class StateSnapshotReader{
 constructor(file){this.file=file;this.lastMtimeMs=0;}
 poll(onEvent){if(!this.file||!fs.existsSync(this.file))return;const st=fs.statSync(this.file);if(st.mtimeMs===this.lastMtimeMs)return;const text=fs.readFileSync(this.file,'utf8');if(!text.endsWith('\n'))return;this.lastMtimeMs=st.mtimeMs;for(const line of text.split(/\r?\n/)){if(!line.trim())continue;const e=parseEventLine(line);if(e)onEvent(e);}}
}
class CommandSnapshotWriter{
 constructor(file,{initialSeq=Date.now()*1000}={}){this.file=file;this.seq=initialSeq;this.latest=new Map();fs.mkdirSync(path.dirname(file),{recursive:true});this._write();}
 _write(){const lines=[...this.latest.values()].sort((a,b)=>a.seq-b.seq).map(formatCommand);const tmp=this.file+'.tmp';fs.writeFileSync(tmp,lines.length?lines.join('\n')+'\n':'');try{fs.renameSync(tmp,this.file);}catch(err){if(!['EEXIST','EPERM','EACCES'].includes(err.code))throw err;fs.rmSync(this.file,{force:true});fs.renameSync(tmp,this.file);}}
 submit(cmd){if(!cmd||!cmd.type)throw new TypeError('command type required');const key=cmd.npcId||`__${cmd.type}`;const record={...cmd,seq:Number.isSafeInteger(cmd.seq)?cmd.seq:++this.seq};this.latest.set(key,record);this._write();return record.seq;}
 remove(npcId){if(this.latest.delete(npcId))this._write();}
 prune(activeIds){const active=new Set(activeIds||[]);let changed=false;for(const key of [...this.latest.keys()]){if(key.startsWith('__'))continue;if(!active.has(key)){this.latest.delete(key);changed=true;}}if(changed)this._write();}
}
function deepMerge(base,override){if(!override||typeof override!=='object'||Array.isArray(override))return base;const out={...base};for(const [k,v] of Object.entries(override)){if(v&&typeof v==='object'&&!Array.isArray(v)&&base?.[k]&&typeof base[k]==='object'&&!Array.isArray(base[k]))out[k]=deepMerge(base[k],v);else out[k]=v;}return out;}
function readJsonFile(file){let text=fs.readFileSync(file,'utf8');if(text.charCodeAt(0)===0xFEFF)text=text.slice(1);return JSON.parse(text);}
function loadConfig(){const p=process.env.TESLES_NPC_CONFIG||path.join(__dirname,'..','config','default.json');let base=readJsonFile(p);const userPath=process.env.TESLES_NPC_USER_CONFIG||path.join(path.dirname(p),'user.json');if(fs.existsSync(userPath)){const user=readJsonFile(userPath);base=deepMerge(base,user);}const cfgDir=path.dirname(p);for(const k of ['eventsFile','commandsFile','offsetFile','stateFile'])if(base.ipc?.[k]&&!path.isAbsolute(base.ipc[k]))base.ipc[k]=path.resolve(cfgDir,base.ipc[k]);return base;}
function physicalControlReady(cfg,director){const mode=cfg.features?.takeoverMode;const modeReady=(mode==='full'||mode==='auto')&&director.world.capabilities?.full_takeover_ready?.ok===true;return cfg.features?.takeoverRequested===true&&modeReady&&director.world.capabilities?.bridge_scheduler?.ok===true&&director.world.capabilities?.brain_stop?.ok===true&&director.world.capabilities?.movement?.ok===true;}
function startMain(){const cfg=loadConfig();const stateFile=process.env.TESLES_NPC_WORLD||path.resolve(__dirname,'..','..','runtime','world.json');const prior=loadWorld(stateFile);const director=new WorldDirector({seed:cfg.world.seed,world:prior,featureFlags:cfg.features,simulation:cfg.simulation,population:cfg.population});const reader=new FileIpcReader(cfg.ipc.eventsFile,cfg.ipc.offsetFile);const stateReader=new StateSnapshotReader(cfg.ipc.stateFile);const commandWriter=new CommandSnapshotWriter(cfg.ipc.commandsFile);const tick=()=>{reader.poll(e=>director.ingest(e));stateReader.poll(e=>director.ingest(e));director.tick(cfg.world.tickMs/1000);const activeRuntimeIds=Object.values(director.world.npcs).filter(n=>n.alive&&n.materialized&&n.runtimeId).map(n=>n.runtimeId);commandWriter.prune(activeRuntimeIds);if(physicalControlReady(cfg,director)){for(const n of Object.values(director.world.npcs)){if(n.aiIntent&&n.materialized){commandWriter.submit(n.aiIntent);n.aiIntent=null;}}}else{for(const n of Object.values(director.world.npcs))n.aiIntent=null;}};setInterval(tick,cfg.world.tickMs).unref();setInterval(()=>saveWorld(stateFile,director.world),cfg.world.autosaveSeconds*1000).unref();process.on('SIGINT',()=>{saveWorld(stateFile,director.world);process.exit(0)});process.on('SIGTERM',()=>{saveWorld(stateFile,director.world);process.exit(0)});const publicDir=path.resolve(__dirname,'..','..','web','public');const server=createHttpServer({director,publicDir,mapConfig:cfg.map});server.listen(cfg.server.port,cfg.server.host,()=>console.log(`[TeslesNPC] Brain+Map http://${cfg.server.host}:${cfg.server.port}`));return{director,server};}
if(require.main===module)startMain();
module.exports={buildTeleportCommand,createHttpServer,FileIpcReader,StateSnapshotReader,CommandSnapshotWriter,deepMerge,loadConfig,startMain,physicalControlReady,safeStaticFile};
