#!/usr/bin/env python3
"""Builds world/poi_data.lua from the hand-marked SCUM map.

tools/poi_source.json holds every marker found on the 25 sector screenshots of
the community SCUM map (one screenshot per sector, D4 top-left to Z0
bottom-right): villages, hunting towers, bunkers, abandoned bunkers, research
facilities, outposts and named points of interest. Each screenshot was
registered against livemap/map/scum_map.png and sits on its sector to within
one base-map pixel, so a marker's pixel position maps straight to world
coordinates through the same calibration the mod and the live map use.

Pins are anchored at their tip; rings at their centre.
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MOD = os.path.join(ROOT, "package", "mod", "TeslesNPCOverhaul")
NAV = os.path.join(MOD, "world", "navgrid_data.lua")
OUT = os.path.join(MOD, "world", "poi_data.lua")
MAP_OUT = os.path.join(ROOT, "package", "livemap", "pois.js")

ROWS, COLS = "DCBAZ", "43210"

# kind -> (radius UU, selection weight, label)
KIND = {
    "CITY":             (28000, 1.35, "City"),
    "VILLAGE":          (9000,  1.00, "Village"),
    "HUNTING":          (2500,  0.90, "Hunting Tower"),
    "MILITARY":         (16000, 1.25, "Military"),
    "BUNKER":           (5000,  1.30, "Bunker"),
    "ABANDONED_BUNKER": (5000,  1.30, "Abandoned Bunker"),
    "RESEARCH":         (6000,  1.30, "Research Facility"),
    "INDUSTRIAL":       (10000, 1.00, "Industrial"),
    "MEDICAL":          (9000,  1.10, "Medical"),
    "LANDMARK":         (5000,  0.70, "Landmark"),
    "OUTPOST":          (30000, 0.00, "Outpost"),
}


def calibration():
    text = open(NAV).read()
    vals = {}
    for key in ("xWest", "xEast", "yNorth", "ySouth"):
        vals[key] = float(re.search(key + r"=([-0-9.]+)", text).group(1))
    return vals


def main():
    cal = calibration()
    span_x = cal["xWest"] - cal["xEast"]
    span_y = cal["yNorth"] - cal["ySouth"]
    src = json.load(open(os.path.join(HERE, "poi_source.json")))
    counters = {}
    points = []
    for o in src:
        ri, ci = ROWS.index(o["sector"][0]), COLS.index(o["sector"][1])
        u = (ci + o["px"] / o["W"]) / 5.0
        v = (ri + o["py"] / o["H"]) / 5.0
        x = cal["xWest"] - u * span_x
        y = cal["yNorth"] - v * span_y
        kind = o["kind"]
        radius, weight, label = KIND[kind]
        key = (o["sector"], kind)
        counters[key] = counters.get(key, 0) + 1
        n = counters[key]
        name = o.get("name") or ("%s %s %d" % (o["sector"], label, n) if kind in ("VILLAGE", "HUNTING")
                                 else "%s %s" % (o["sector"], label) if n == 1
                                 else "%s %s %d" % (o["sector"], label, n))
        pid = "%s_%s_%02d" % (kind[:3], o["sector"], n)
        points.append((pid, name, o["sector"], kind, x, y, weight, radius))

    with open(OUT, "w") as f:
        f.write("-- TESLES NPC OVERHAUL - points of interest (generated)\n")
        f.write("-- Built by tools/build_pois.py from tools/poi_source.json: the\n")
        f.write("-- hand-marked community SCUM map, one screenshot per sector.\n")
        f.write("-- Do not hand edit; regenerate instead.\n")
        f.write("return {\n  points={\n")
        for pid, name, sec, kind, x, y, w, r in points:
            f.write('    {id="%s",label="%s",sector="%s",kind="%s",x=%d,y=%d,weight=%.2f,radius=%d},\n'
                    % (pid, name.replace('"', "'"), sec, kind, round(x), round(y), w, r))
        f.write("  },\n}\n")
    # The live map draws the same places as its POI layer.
    rows = [{"id": pid, "n": name, "k": kind, "x": round(x), "y": round(y)}
            for pid, name, sec, kind, x, y, w, r in points]
    with open(MAP_OUT, "w") as f:
        f.write("// Generated by tools/build_pois.py - do not hand edit.\n")
        f.write("window.TESLES_POIS=" + json.dumps(rows, separators=(",", ":")) + ";\n")
    print("wrote %d points to %s" % (len(points), OUT))


if __name__ == "__main__":
    main()
